name: Apply Supabase Migrations

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: read # This is required for actions/checkout

jobs:
  apply-migrations:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
      SUPABASE_AUTH_GOOGLE_CLIENT_ID:
        ${{ secrets.SUPABASE_AUTH_GOOGLE_CLIENT_ID }}
      SUPABASE_AUTH_GOOGLE_CLIENT_SECRET:
        ${{ secrets.SUPABASE_AUTH_GOOGLE_CLIENT_SECRET }}
      SUPABASE_AUTH_GITHUB_CLIENT_ID:
        ${{ secrets.SUPABASE_AUTH_GITHUB_CLIENT_ID }}
      SUPABASE_AUTH_GITHUB_CLIENT_SECRET:
        ${{ secrets.SUPABASE_AUTH_GITHUB_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: npm install
        run: npm install

      - name: Supabase link project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Apply Supabase migrations on production
        run: supabase db push
